-- CREATE DATABASE QuanLyDatHang;
-- USE QuanLyDatHang;
CREATE TABLE KhachHang (
	MSKH CHARACTER(20),
   	HoTenKH VARCHAR(40),
    Email TEXT,
	SoDienThoai VARCHAR(12),
    MatKhau char(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (MSKH)
);
CREATE TABLE DiaChiKH (
    MaDC CHARACTER(22),
    MSKH CHARACTER(20),
    DiaChi VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (MaDC, MSKH),
    FOREIGN KEY (MSKH) REFERENCES khachHang(MSKH) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE NhanVien (
	MSNV CHARACTER(20),
	HoTenNV VARCHAR(40),
	ChucVu VARCHAR(40),
    DiaChi VARCHAR(50),
    SoDienThoai VARCHAR(12),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (MSNV)
);
CREATE TABLE category (
	code_category CHARACTER(3),
    name_category VARCHAR(60),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (code_category)
);
CREATE TABLE LoaiHangHoa (
	MaLoaiHang CHARACTER(5),
    TenLoaiHang VARCHAR(60),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (MaLoaiHang)
);
CREATE TABLE HangHoa (
	MSHH CHARACTER(5),
    TenHH VARCHAR(100),
    QuyCach VARCHAR(100),
    Gia DECIMAL(19),
    SoLuongHang INT(5),
    GhiChu VARCHAR(5000),
    thumbnail VARCHAR(500),
    MaLoaiHang CHARACTER(5),
    code_category CHARACTER(3),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (MSHH),
    FOREIGN KEY (MaLoaiHang) REFERENCES LoaiHangHoa(MaLoaiHang) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (code_category) REFERENCES category(code_category) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE DatHang (
	SoDonDH INT(11),
    MSKH CHARACTER(20),
    NgayDH DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (SoDonDH),
    FOREIGN KEY (MSKH) REFERENCES KhachHang(MSKH) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE ChiTietDatHang (
    SoDonDH INT(11),
    MSHH CHARACTER(5),
    Gia Decimal(19),
    SoLuong INT(5),
    GiaDatHang DECIMAL(19),
    GiamGia DECIMAL (5) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 
    PRIMARY KEY (SoDonDH, MSHH),
    FOREIGN KEY (SoDonDH) REFERENCES DatHang(SoDonDH) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (MSHH) REFERENCES HangHoa(MSHH) ON UPDATE CASCADE ON DELETE CASCADE
);
-- -------------------------------------------------------------------------------------------------
ALTER TABLE category ENGINE=InnoDB;
ALTER TABLE ChiTietDatHang ENGINE=InnoDB;
ALTER TABLE DatHang ENGINE=InnoDB;
ALTER TABLE DiaChiKH ENGINE=InnoDB;
ALTER TABLE HangHoa ENGINE=InnoDB;
ALTER TABLE KhachHang ENGINE=InnoDB;
ALTER TABLE LoaiHangHoa ENGINE=InnoDB;
ALTER TABLE NhanVien ENGINE=InnoDB;
-- -------------------------------------------------------------------------------------------------
ALTER TABLE category CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE ChiTietDatHang CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE DatHang CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE DiaChiKH CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE HangHoa CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE KhachHang CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE LoaiHangHoa CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE NhanVien CONVERT TO CHARACTER SET utf8mb4;
-- -------------------------------------------------------------------------------------------------
ALTER TABLE DiaChiKH ADD CONSTRAINT FK_DiaChiKH_MSKH
    FOREIGN KEY (MSKH) REFERENCES khachHang(MSKH) ON UPDATE CASCADE ON DELETE CASCADE;
-- 
ALTER TABLE HangHoa ADD CONSTRAINT FK_HangHoa_MaLoaiHang
    FOREIGN KEY (MaLoaiHang) REFERENCES LoaiHangHoa(MaLoaiHang) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE HangHoa ADD CONSTRAINT FK_HangHoa_code_category
    FOREIGN KEY (code_category) REFERENCES category(code_category) ON UPDATE CASCADE ON DELETE CASCADE;
-- 
ALTER TABLE DatHang ADD CONSTRAINT FK_DatHang_MSKH
    FOREIGN KEY (MSKH) REFERENCES KhachHang(MSKH) ON UPDATE CASCADE ON DELETE CASCADE;
-- 
ALTER TABLE ChiTietDatHang ADD CONSTRAINT FK_ChiTietDatHang_SoDonDH
    FOREIGN KEY (SoDonDH) REFERENCES DatHang(SoDonDH) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ChiTietDatHang ADD CONSTRAINT FK_ChiTietDatHang_MSHH
    FOREIGN KEY (MSHH) REFERENCES HangHoa(MSHH) ON UPDATE CASCADE ON DELETE CASCADE;